load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# My repository!
local_repository(
    name = "bzlmodrio-libssh",
    path = "../",
)

# Google Test
http_archive(
    name = "googletest",
    sha256 = "24564e3b712d3eb30ac9a85d92f7d720f60cc0173730ac166f27dda7fed76cb2",
    strip_prefix = "googletest-release-1.12.1",
    urls = ["https://github.com/google/googletest/archive/release-1.12.1.zip"],
)

load("@bzlmodrio-libssh//private/non_bzlmod_dependencies:download_dependencies.bzl", "download_dependencies")

download_dependencies()

load("@bzlmodrio-libssh//private/non_bzlmod_dependencies:setup_dependencies.bzl", "setup_dependencies")

setup_dependencies()

#####################
# Styleguide
#####################
local_repository(
    name = "rules_pmd",
    path = "../../../rules/rules_pmd",
)

local_repository(
    name = "rules_checkstyle",
    path = "../../../rules/rules_checkstyle",
)

local_repository(
    name = "rules_spotless",
    path = "../../../rules/rules_spotless",
)

local_repository(
    name = "rules_wpiformat",
    path = "../../../rules/rules_wpiformat",
)

local_repository(
    name = "rules_wpi_styleguide",
    path = "../../../rules/rules_wpi_styleguide",
)

load("@rules_wpi_styleguide//dependencies:load_rule_dependencies.bzl", "load_styleguide_rule_dependencies")

load_styleguide_rule_dependencies()

load("@rules_wpi_styleguide//dependencies:load_dependencies.bzl", "load_styleguide_dependencies")

load_styleguide_dependencies()

load("@rules_wpi_styleguide//dependencies:setup_styleguide.bzl", "setup_styleguide")

setup_styleguide()

load("@rules_wpi_styleguide//dependencies:load_pins.bzl", "load_styleguide_pins")

load_styleguide_pins()
#####################
