name: Lint and Format

on: [pull_request, push]

jobs:
  lint_python:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
  buildifier:
    name: "buildifier"
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go 1.20.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.x
          cache: false
        id: go

      - uses: actions/checkout@v4

      - name: Install Buildifier
        run: |
          cd $(mktemp -d)
          GO111MODULE=on go install github.com/bazelbuild/buildtools/buildifier@latest

      - name: Run buildifier
        run: buildifier -warnings all --lint=fix -r .

      - name: Check Output
        run: git --no-pager diff --exit-code HEAD

      - name: Generate diff
        run: git diff HEAD > buildifier-fixes.patch
        if: ${{ failure() }}

      - uses: actions/upload-artifact@v4
        with:
          name: buildifier fixes
          path: buildifier-fixes.patch
        if: ${{ failure() }}
